# Generated by Django 4.2.2 on 2023-07-11 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ano_lanzamiento', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('desarrollador', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('puntuacion', models.FloatField()),
                ('modos_juego', models.CharField(max_length=100)),
                ('requisitos_sistema', models.TextField()),
                ('imagen_portada', models.URLField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('plataforma_distribucion', models.CharField(max_length=50)),
                ('idioma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.videojuego')),
            ],
        ),
    ]
