# Generated by Django 4.2.2 on 2023-07-12 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_videojuego_recomendacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='puntuacion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
