# Generated by Django 4.2.2 on 2023-07-12 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_videojuego_puntuacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='imagen_portada',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='modos_juego',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='plataforma_distribucion',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='recomendacion',
            name='puntuacion',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('rol', 'RPG'), ('estrategia', 'Estrategia'), ('deporte', 'Deporte'), ('disparos', 'Disparos'), ('plataformas', 'Plataformas'), ('simulacion', 'Simulación'), ('puzzle', 'Puzzle')], max_length=50),
        ),
    ]
